package compiler

import (
	"github.com/Zac-Garby/radon/ast"
	"github.com/Zac-Garby/radon/object"
)

// A Compiler translates an AST into some bytecode.
type Compiler struct {
	// The generated bytecode
	Bytes []byte

	Constants []object.Object
	Names     []string
	Jumps     []int
}

// New instantiates a new Compiler instance.
func New() *Compiler {
	return &Compiler{
		Bytes:     make([]byte, 0, 256),
		Constants: make([]object.Object, 0, 8),
		Names:     make([]string, 0, 8),
		Jumps:     make([]int, 8),
	}
}

// Compile compiles an ast.Program into bytecode, returning
// any errors. The bytecode, constants, and names, are stored
// in the Compiler instance in the respective fields.
func (c *Compiler) Compile(p *ast.Program) error {
	for _, stmt := range p.Statements {
		if err := c.CompileStatement(stmt); err != nil {
			return err
		}
	}

	return nil
}
