<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>rn</string>
	</array>
	<key>name</key>
	<string>Radon</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(return|if|then|else|while|for|do|end|next|break|match|model|where|import|in)\b</string>
			<key>name</key>
			<string>keyword.control.radon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(nil|true|false)\b</string>
			<key>name</key>
			<string>constant.language.radon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(print(ln)?|len|typeof|modelof|str|num|list|tuple|round|floor|ceil|sleep|assert)\b</string>
			<key>name</key>
			<string>constant.language.builtin.radon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.radon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\["nabfrtv]</string>
					<key>name</key>
					<string>constant.character.escape.radon</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single.radon</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\["nabfrtv]</string>
					<key>name</key>
					<string>constant.character.escape.radon</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b\d+(?:\.\d+)?</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.radon</string>
		</dict>
		<dict>
			<key>match</key>
			<string>-&gt;|=&gt;|\||:|:?=|\.</string>
			<key>name</key>
			<string>keyword.operator.radon</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.radon</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.radon</string>
	<key>uuid</key>
	<string>D3B87850-1FFB-4CD8-94FE-3493462AF946</string>
</dict>
</plist>
